---
# ^^ signifies it is a yml file
name: Checks

on: [push]

jobs: 
  # id of the job
  test-lint:
    name: Test and Lint
    # docker already installed in this ubuntu version
    runs-on: ubuntu-20.04
    steps:
      - name: Login to Docker Hub
        # another premade action .. reuse action .. docker container with configuration to do a certain task
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        # action to check out code in github
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: docker-compose run --rm app sh -c "python manage.py test"
      - name: Lint
        run: docker-compose run --rm app sh -c "flake8"